theme: jekyll-theme-minimal
title: Nandu's HomePage
description: Welcome to Nandu's HomePage! I'm Nandu, a developer, self-taught beginner and passionate about IT. By the way, I'm mainly "specialized" in javascript and python.
